[
  {
    id: 'blue-dream',
    name: 'Blue Dream',
    type: 'hybrid',
    thc: 21.0,
    cbd: 0.1,
    terpenes: [
      { name: 'Myrcene', pct: 0.52, effect: 'Relaxing, sedating, earthy musk' },
      { name: 'Pinene', pct: 0.31, effect: 'Alertness, memory retention, piney freshness' },
      { name: 'Caryophyllene', pct: 0.22, effect: 'Anti-inflammatory, spicy, stress relief' },
    ],
    effects: ['Creative', 'Euphoric', 'Happy', 'Relaxed'],
    flavors: ['Berry', 'Blueberry', 'Sweet', 'Herbal'],
    lineage: { mother: 'Blueberry', father: 'Haze' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '21.0%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'THCA', value: '23.8%' },
        { name: 'CBG', value: '0.4%' },
        { name: 'CBN', value: '0.1%' },
      ],
    },
    dispensaryIds: ['green-needle', 'have-a-heart-belltown', 'happy-leaf'],
    likeCount: 52000,
    chemotype: 'Type I (THC-dominant)',
    description:
      'A sativa-dominant hybrid born on the foggy California coast and fully claimed by the Pacific Northwest\'s creative culture. Blue Dream drifts in like morning marine layer — blueberry sweetness rising into a cerebral lift that clears space for ideas without walling off the body\'s ease. The strain that taught a generation of Seattle and Portland flower shops what balance actually means.',
    color: '#5B8DD9',
    source_state: 'WA',
  },
  {
    id: 'gg4',
    name: 'GG#4',
    type: 'hybrid',
    thc: 26.0,
    cbd: 0.1,
    terpenes: [
      { name: 'Caryophyllene', pct: 0.58, effect: 'Spicy, peppery, anti-inflammatory' },
      { name: 'Myrcene', pct: 0.44, effect: 'Earthy, sedating, muscle relaxation' },
      { name: 'Limonene', pct: 0.29, effect: 'Citrus lift, mood elevation, stress relief' },
    ],
    effects: ['Relaxed', 'Euphoric', 'Sleepy', 'Hungry'],
    flavors: ['Earthy', 'Pine', 'Pungent', 'Sour'],
    lineage: { mother: 'Chem\'s Sister', father: 'Sour Dubb' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '26.0%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'THCA', value: '29.5%' },
        { name: 'CBG', value: '0.5%' },
        { name: 'CBN', value: '0.2%' },
      ],
    },
    dispensaryIds: ['shawn-kemps', 'dockside-sodo', 'gorge-greens'],
    likeCount: 40000,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Heavy as Cascade snowpack and twice as persistent, GG#4 is the strain that turned "glued to the couch" into a wellness ritual for tired bodies up and down I-5. Chunky resin-lacquered buds carry an earthy diesel funk that hits like a cold rain — sudden, total, and transformative. Born from Chem genetics, it found its spiritual home among the tired Cascadian faithful who believe full-body release is its own form of medicine.',
    color: '#5C7A3E',
    source_state: 'WA',
  },
  {
    id: 'gelato-41',
    name: 'Gelato 41',
    type: 'hybrid',
    thc: 23.0,
    cbd: 0.1,
    terpenes: [
      { name: 'Caryophyllene', pct: 0.61, effect: 'Spicy warmth, pain modulation, calming' },
      { name: 'Limonene', pct: 0.38, effect: 'Citrus brightness, anti-anxiety, mood lift' },
      { name: 'Humulene', pct: 0.19, effect: 'Earthy, appetite suppressing, anti-inflammatory' },
      { name: 'Linalool', pct: 0.14, effect: 'Floral calm, sedation, stress relief' },
    ],
    effects: ['Euphoric', 'Relaxed', 'Creative', 'Happy'],
    flavors: ['Sweet', 'Citrus', 'Creamy', 'Berry'],
    lineage: { mother: 'Sunset Sherbet', father: 'Thin Mint GSC' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '23.0%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'THCA', value: '26.1%' },
        { name: 'CBG', value: '0.6%' },
        { name: 'CBN', value: '0.1%' },
      ],
    },
    dispensaryIds: ['cascadia-collective', 'farma', 'chalice-downtown'],
    likeCount: 35000,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Gelato 41 arrives at the senses the way a late-summer Portland evening does — deep purples in the bud, a creamy sweetness that lingers like the last scoop before closing time, and a warmth that settles from the shoulders down. The balanced euphoria sits right at the edge of productive and pleasantly lost, making it the craft-focused dispensary\'s answer to those who refuse to choose between function and indulgence. Cookie genetics refined to their finest expression.',
    color: '#7B5EA7',
    source_state: 'OR',
  },
  {
    id: 'wedding-cake',
    name: 'Wedding Cake',
    type: 'hybrid',
    thc: 24.0,
    cbd: 0.1,
    terpenes: [
      { name: 'Caryophyllene', pct: 0.64, effect: 'Peppery depth, anti-inflammatory, grounding' },
      { name: 'Limonene', pct: 0.41, effect: 'Tangy uplift, mood brightening, stress reduction' },
      { name: 'Myrcene', pct: 0.33, effect: 'Musky sweetness, body relaxation, sedation' },
    ],
    effects: ['Relaxed', 'Euphoric', 'Hungry', 'Happy'],
    flavors: ['Vanilla', 'Pepper', 'Butter', 'Earthy'],
    lineage: { mother: 'Triangle Kush', father: 'Animal Mints' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '24.0%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'THCA', value: '27.2%' },
        { name: 'CBG', value: '1.0%' },
        { name: 'CBN', value: '0.1%' },
      ],
    },
    dispensaryIds: ['have-a-heart-belltown', 'green-needle', 'chalice-downtown'],
    likeCount: 38000,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Leafly\'s 2019 Strain of the Year carries the rich, tangy weight of a celebration you didn\'t have to plan — vanilla-pepper sweetness rising from dense, crystal-frosted buds that look like they were dusted in Pacific sea salt. Wedding Cake\'s indica-leaning warmth unwraps the body methodically from the shoulders to the ankles, letting the mind float just far enough above the noise to call it a good evening. Boutique dispensary shelves from Belltown to Portland\'s Pearl District move this one fast for a reason.',
    color: '#E8D5A3',
    source_state: 'WA',
  },
  {
    id: 'northern-lights',
    name: 'Northern Lights',
    type: 'indica',
    thc: 18.0,
    cbd: 0.1,
    terpenes: [
      { name: 'Myrcene', pct: 0.55, effect: 'Deep body calm, earthy sedation, sleep aid' },
      { name: 'Caryophyllene', pct: 0.34, effect: 'Spicy warmth, pain relief, anti-anxiety' },
      { name: 'Limonene', pct: 0.21, effect: 'Subtle citrus, mood balance, stress lift' },
    ],
    effects: ['Sleepy', 'Relaxed', 'Euphoric', 'Hungry'],
    flavors: ['Pine', 'Earthy', 'Woody', 'Sweet'],
    lineage: { mother: 'Afghani', father: 'Thai' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '18.0%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'THCA', value: '20.4%' },
        { name: 'CBG', value: '1.0%' },
        { name: 'CBN', value: '0.2%' },
      ],
    },
    dispensaryIds: ['shawn-kemps', 'rainforest-remedies', 'gorge-greens'],
    likeCount: 45000,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Rumor has it Northern Lights first reached its roots into Puget Sound soil before Holland\'s Sensi Seeds carried it to legend — and the PNW has never stopped feeling that quiet ownership. Pure Afghani-dominant resin architecture wraps the body in the kind of dense, piney warmth that only comes from old-growth forests and serious genetics. This is the strain that turns a Washington winter night into something worth sinking into.',
    color: '#2E5E4E',
    source_state: 'WA',
  },
  {
    id: 'granddaddy-purple',
    name: 'Granddaddy Purple',
    type: 'indica',
    thc: 17.0,
    cbd: 0.1,
    terpenes: [
      { name: 'Myrcene', pct: 0.57, effect: 'Grape-musky calm, body lock, sleep onset' },
      { name: 'Pinene', pct: 0.30, effect: 'Pine clarity, memory, airway opening' },
      { name: 'Caryophyllene', pct: 0.24, effect: 'Spicy undertone, pain modulation, anti-stress' },
    ],
    effects: ['Sleepy', 'Relaxed', 'Euphoric', 'Hungry'],
    flavors: ['Grape', 'Berry', 'Floral', 'Sweet'],
    lineage: { mother: 'Mendo Purps', father: 'Afghani' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '17.0%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'THCA', value: '19.3%' },
        { name: 'CBG', value: '0.4%' },
        { name: 'CBN', value: '0.3%' },
      ],
    },
    dispensaryIds: ['shawn-kemps', 'happy-leaf', 'rainforest-remedies'],
    likeCount: 42000,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Ken Estes\'s 2003 California masterwork found its most devoted congregation in the Pacific Northwest, where the long grey evenings create the perfect condition for GDP\'s royal purple hues and grape-laden embrace. Deep myrcene-forward sedation arrives with a cerebral warmth that makes the ceiling seem very far away in the best possible sense — the Oregon coast\'s way of saying the day is done and rest is earned. No other indica communicates closure quite as eloquently.',
    color: '#6B3FA0',
    source_state: 'OR',
  },
  {
    id: 'sour-diesel',
    name: 'Sour Diesel',
    type: 'sativa',
    thc: 22.0,
    cbd: 0.2,
    terpenes: [
      { name: 'Caryophyllene', pct: 0.48, effect: 'Peppery fuel note, anti-inflammatory, focus' },
      { name: 'Myrcene', pct: 0.33, effect: 'Earthy base, body ease, edge softening' },
      { name: 'Limonene', pct: 0.29, effect: 'Citrus charge, mood elevation, mental clarity' },
      { name: 'Terpinolene', pct: 0.17, effect: 'Herbal uplift, energizing, pine-fresh' },
    ],
    effects: ['Energetic', 'Euphoric', 'Creative', 'Focused'],
    flavors: ['Diesel', 'Citrus', 'Earthy', 'Herbal'],
    lineage: { mother: 'Chemdog 91', father: 'Super Skunk' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '22.0%' },
        { name: 'CBD', value: '0.2%' },
        { name: 'THCA', value: '24.9%' },
        { name: 'CBG', value: '0.5%' },
        { name: 'CBN', value: '0.1%' },
      ],
    },
    dispensaryIds: ['green-needle', 'dockside-sodo', 'farma'],
    likeCount: 48000,
    chemotype: 'Type I (THC-dominant)',
    description:
      'East Coast in origin but Pacific Northwest in attitude — Sour Diesel hits like the first espresso of a grey Seattle morning, all fuel and forward motion with nowhere to be but fully, electrically present. The sharp diesel-citrus punch clears mental fog like a Columbia Gorge wind event, leaving behind a fast-moving cerebral energy that creative professionals and trail runners up and down the coast have relied on for decades. Nothing about this strain apologizes for wanting to get things done.',
    color: '#D4A017',
    source_state: 'WA',
  },
  {
    id: 'acdc',
    name: 'ACDC',
    type: 'hybrid',
    thc: 1.0,
    cbd: 20.0,
    terpenes: [
      { name: 'Myrcene', pct: 0.44, effect: 'Grounding calm, anti-inflammatory, relaxation without intoxication' },
      { name: 'Pinene', pct: 0.38, effect: 'Mental clarity, airway support, alertness' },
      { name: 'Caryophyllene', pct: 0.27, effect: 'Anti-inflammatory, analgesic, gentle body warmth' },
      { name: 'Ocimene', pct: 0.12, effect: 'Sweet floral lift, subtle mood support' },
    ],
    effects: ['Relaxed', 'Focused', 'Happy', 'Uplifted'],
    flavors: ['Earthy', 'Woody', 'Pine', 'Sweet'],
    lineage: { mother: 'Cannatonic', father: null },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '1.0%' },
        { name: 'CBD', value: '20.0%' },
        { name: 'THCA', value: '1.1%' },
        { name: 'CBDA', value: '22.7%' },
        { name: 'CBG', value: '0.3%' },
      ],
    },
    dispensaryIds: ['rainforest-remedies', 'cascadia-collective', 'gorge-greens'],
    likeCount: 18000,
    chemotype: 'Type III (CBD-dominant)',
    description:
      'ACDC is the strain that reshaped what Pacific Northwest wellness dispensaries are for — a near-CBD-pure cultivar that delivers therapeutic depth without a whisper of intoxication, perfect for the Olympia wellness community that takes its medicine seriously. Cannatonic heritage gives it a clean earthy-pine profile, and the anxiety and inflammation relief it provides has made it the go-to for patients who want the plant\'s gifts without any interruption to their day. Oregon\'s craft CBD growers have elevated this cultivar into a regional specialty.',
    color: '#4A7A55',
    source_state: 'OR',
  },
  {
    id: 'harlequin',
    name: 'Harlequin',
    type: 'hybrid',
    thc: 7.0,
    cbd: 12.0,
    terpenes: [
      { name: 'Myrcene', pct: 0.46, effect: 'Mellow body ease, earthy warmth, gentle sedation' },
      { name: 'Caryophyllene', pct: 0.35, effect: 'Anti-inflammatory, spicy roundness, pain relief' },
      { name: 'Pinene', pct: 0.28, effect: 'Mental alertness, counteracts THC cloudiness, fresh pine' },
    ],
    effects: ['Relaxed', 'Focused', 'Happy', 'Uplifted'],
    flavors: ['Earthy', 'Mango', 'Woody', 'Citrus'],
    lineage: { mother: 'Colombian Gold', father: 'Nepali' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '7.0%' },
        { name: 'CBD', value: '12.0%' },
        { name: 'THCA', value: '7.9%' },
        { name: 'CBDA', value: '13.6%' },
        { name: 'CBG', value: '0.4%' },
      ],
    },
    dispensaryIds: ['rainforest-remedies', 'farma', 'cascadia-collective'],
    likeCount: 20000,
    chemotype: 'Type II (Balanced CBD/THC)',
    description:
      'Harlequin is the strain that finally gave the Pacific Northwest\'s medical community a bridge between worlds — enough THC to feel the plant\'s social warmth, enough CBD to keep the mind clear and the body easy through a full workday in the rain. The mango-earth terpene profile carries a quiet exoticism from its Colombian and Nepali landrace ancestry, grounded by the clean air of Oregon\'s Willamette Valley where it thrives. Farma and the region\'s curated wellness shops consider it essential stock for the clear-headed patient.',
    color: '#E8A44A',
    source_state: 'OR',
  },
  {
    id: 'jack-herer',
    name: 'Jack Herer',
    type: 'sativa',
    thc: 18.0,
    cbd: 0.1,
    terpenes: [
      { name: 'Terpinolene', pct: 0.52, effect: 'Floral-herbal uplift, energizing, creativity driver' },
      { name: 'Pinene', pct: 0.36, effect: 'Pine clarity, memory retention, bronchial opening' },
      { name: 'Caryophyllene', pct: 0.24, effect: 'Spicy depth, anti-inflammatory, stress buffer' },
      { name: 'Ocimene', pct: 0.15, effect: 'Sweet herbal brightness, antifungal, uplifting' },
    ],
    effects: ['Creative', 'Energetic', 'Euphoric', 'Focused'],
    flavors: ['Pine', 'Earthy', 'Woody', 'Spicy'],
    lineage: { mother: 'Northern Lights #5', father: 'Shiva Skunk' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '18.0%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'THCA', value: '20.4%' },
        { name: 'CBG', value: '0.6%' },
        { name: 'CBN', value: '0.1%' },
      ],
    },
    dispensaryIds: ['green-needle', 'cascadia-collective', 'dockside-sodo'],
    likeCount: 44000,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Named for the cannabis activist and author who believed the plant could change the world, Jack Herer carries that conviction in its terpene profile — a bright Sensi Seeds pedigree of pine, spice, and herbal focus that feels less like getting high and more like getting clear. The strain connects naturally to the Pacific Northwest\'s activist and outdoor culture, where its energizing terpinolene-forward lift pairs equally well with a morning trail run in the Olympics or an afternoon of ideation at a Portland co-working space. This is the people\'s strain for the conscious consumer.',
    color: '#8B7355',
    source_state: 'WA',
  },
]
