// Untapped Market — Mock data extracted from the prototype HTML.
// Source: untapped-market.html lines 1247-1551.
// Treat the projection doc (UNTAPPED_MARKET_PROJECT_PROJECTION.md) as the source
// of truth for shapes; this file holds the 6 strains + 4 dispensaries + 3 trip
// reports referenced there.

import type {
  Dispensary,
  MediaItem,
  Strain,
  TripReport,
  UserProfile,
} from './types';

export const STRAINS: Strain[] = [
  {
    id: 'cascadia-haze',
    name: 'Cascadia Haze',
    type: 'sativa',
    thc: 23.4,
    cbd: 0.2,
    chemotype: 'Type I (THC-dominant)',
    description:
      'A bright, cerebral sativa born in the foggy lowlands of the Cascades. Cascadia Haze carries the sharp citrus snap of Pacific air with a golden morning energy that keeps creative momentum flowing without the crash.',
    terpenes: [
      { name: 'Terpinolene', pct: 1.42, effect: 'Uplifting' },
      { name: 'Myrcene', pct: 0.98, effect: 'Relaxing' },
      { name: 'Ocimene', pct: 0.76, effect: 'Energizing' },
      { name: 'Caryophyllene', pct: 0.54, effect: 'Anti-inflammatory' },
    ],
    effects: ['Euphoric', 'Creative', 'Focused', 'Energetic'],
    flavors: ['Citrus', 'Pine', 'Floral', 'Earthy'],
    lineage: { mother: 'Haze', father: 'Pacific Ghost' },
    labData: {
      lab: 'Confidence Analytics',
      date: '2025-10-14',
      cannabinoids: [
        { name: 'THC', value: '23.4%' },
        { name: 'THCA', value: '26.2%' },
        { name: 'CBD', value: '0.2%' },
        { name: 'CBDA', value: '0.3%' },
        { name: 'CBG', value: '0.9%' },
        { name: 'CBN', value: '0.1%' },
        { name: 'CBC', value: '0.4%' },
        { name: 'THCV', value: '0.3%' },
      ],
    },
    dispensaryIds: ['green-needle', 'cascadia-collective'],
    likeCount: 847,
    color: '#d4a853',
  },
  {
    id: 'rainier-kush',
    name: 'Rainier Kush',
    type: 'indica',
    thc: 28.1,
    cbd: 0.1,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Named for the mountain that watches over the Puget Sound, Rainier Kush is a heavy, earthen indica with the deep resin of old-growth forest. Expect a full-body release and a long, peaceful night.',
    terpenes: [
      { name: 'Myrcene', pct: 1.85, effect: 'Sedating' },
      { name: 'Linalool', pct: 1.12, effect: 'Calming' },
      { name: 'Caryophyllene', pct: 0.89, effect: 'Anti-inflammatory' },
      { name: 'Humulene', pct: 0.67, effect: 'Appetite suppressant' },
    ],
    effects: ['Relaxed', 'Sleepy', 'Happy', 'Hungry'],
    flavors: ['Earthy', 'Pine', 'Diesel', 'Grape'],
    lineage: { mother: 'OG Kush', father: 'Skywalker' },
    labData: {
      lab: 'Trace Analytics',
      date: '2025-11-02',
      cannabinoids: [
        { name: 'THC', value: '28.1%' },
        { name: 'THCA', value: '31.5%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'CBDA', value: '0.1%' },
        { name: 'CBG', value: '0.7%' },
        { name: 'CBN', value: '0.4%' },
        { name: 'CBC', value: '0.2%' },
        { name: 'THCV', value: '0.1%' },
      ],
    },
    dispensaryIds: ['green-needle', 'rainforest-remedies'],
    likeCount: 1204,
    color: '#8b6fb8',
  },
  {
    id: 'hood-river-haze',
    name: 'Hood River Haze',
    type: 'hybrid',
    thc: 19.7,
    cbd: 0.5,
    chemotype: 'Type I (THC-dominant)',
    description:
      'A balanced hybrid born at the intersection of river valley and volcanic ridge. Hood River Haze opens with a sativa clarity and settles into a mellow indica warmth — ideal for the long PNW evening.',
    terpenes: [
      { name: 'Limonene', pct: 1.23, effect: 'Mood elevation' },
      { name: 'Pinene', pct: 0.95, effect: 'Alertness' },
      { name: 'Myrcene', pct: 0.78, effect: 'Relaxing' },
      { name: 'Terpinolene', pct: 0.54, effect: 'Uplifting' },
    ],
    effects: ['Happy', 'Creative', 'Relaxed', 'Talkative'],
    flavors: ['Lemon', 'Apple', 'Spice', 'Floral'],
    lineage: { mother: 'Cascadia Haze', father: 'Oregon OG' },
    labData: {
      lab: 'Green Leaf Lab',
      date: '2025-09-28',
      cannabinoids: [
        { name: 'THC', value: '19.7%' },
        { name: 'THCA', value: '22.3%' },
        { name: 'CBD', value: '0.5%' },
        { name: 'CBDA', value: '0.6%' },
        { name: 'CBG', value: '1.1%' },
        { name: 'CBN', value: '0.2%' },
        { name: 'CBC', value: '0.6%' },
        { name: 'THCV', value: '0.2%' },
      ],
    },
    dispensaryIds: ['cascadia-collective', 'gorge-greens'],
    likeCount: 632,
    color: '#7cb87a',
  },
  {
    id: 'olympic-fog',
    name: 'Olympic Fog',
    type: 'hybrid',
    thc: 22.8,
    cbd: 0.3,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Inspired by the perpetual mist rolling off the Olympic Peninsula, this dense hybrid wraps you in calm focus. The terpene stack leans coastal — briney, herbal, and slightly sweet.',
    terpenes: [
      { name: 'Caryophyllene', pct: 1.56, effect: 'Stress relief' },
      { name: 'Linalool', pct: 0.94, effect: 'Calming' },
      { name: 'Myrcene', pct: 0.82, effect: 'Relaxing' },
      { name: 'Humulene', pct: 0.41, effect: 'Anti-anxiety' },
    ],
    effects: ['Relaxed', 'Calm', 'Focused', 'Happy'],
    flavors: ['Herbal', 'Lavender', 'Sweet', 'Woody'],
    lineage: { mother: 'Cookies', father: 'Blue Dream' },
    labData: {
      lab: 'Confidence Analytics',
      date: '2025-10-30',
      cannabinoids: [
        { name: 'THC', value: '22.8%' },
        { name: 'THCA', value: '25.5%' },
        { name: 'CBD', value: '0.3%' },
        { name: 'CBDA', value: '0.4%' },
        { name: 'CBG', value: '0.8%' },
        { name: 'CBN', value: '0.2%' },
        { name: 'CBC', value: '0.5%' },
        { name: 'THCV', value: '0.1%' },
      ],
    },
    dispensaryIds: ['rainforest-remedies', 'green-needle'],
    likeCount: 489,
    color: '#4a9b9e',
  },
  {
    id: 'puget-sound-cbd',
    name: 'Puget Sound CBD',
    type: 'hybrid',
    thc: 1.2,
    cbd: 18.5,
    chemotype: 'Type II (Balanced CBD/THC)',
    description:
      'A high-CBD cultivar crafted for the wellness-focused cannabis consumer. Puget Sound CBD delivers calm clarity without intoxication — perfect for daytime relief, anxiety management, or anyone new to cannabis.',
    terpenes: [
      { name: 'Myrcene', pct: 1.14, effect: 'Relaxing' },
      { name: 'Pinene', pct: 0.88, effect: 'Alertness' },
      { name: 'Linalool', pct: 0.73, effect: 'Calming' },
      { name: 'Humulene', pct: 0.52, effect: 'Anti-inflammatory' },
    ],
    effects: ['Calm', 'Clear-headed', 'Focused', 'Pain relief'],
    flavors: ['Earthy', 'Pine', 'Floral', 'Herbal'],
    lineage: { mother: 'ACDC', father: null },
    labData: {
      lab: 'Trace Analytics',
      date: '2025-11-15',
      cannabinoids: [
        { name: 'THC', value: '1.2%' },
        { name: 'THCA', value: '1.4%' },
        { name: 'CBD', value: '18.5%' },
        { name: 'CBDA', value: '20.8%' },
        { name: 'CBG', value: '0.4%' },
        { name: 'CBN', value: '0.1%' },
        { name: 'CBC', value: '0.8%' },
        { name: 'THCV', value: '0.0%' },
      ],
    },
    dispensaryIds: ['cascadia-collective', 'rainforest-remedies'],
    likeCount: 341,
    color: '#4a9b9e',
  },
  {
    id: 'willamette-valley-og',
    name: 'Willamette Valley OG',
    type: 'indica',
    thc: 26.3,
    cbd: 0.1,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Born in the fertile agricultural valley between the Coast Range and the Cascades. Willamette Valley OG is a bold, resinous indica with notes of fuel and dark fruit. Heavy hitting — for veterans who want the full experience.',
    terpenes: [
      { name: 'Myrcene', pct: 2.01, effect: 'Sedating' },
      { name: 'Caryophyllene', pct: 1.34, effect: 'Anti-inflammatory' },
      { name: 'Limonene', pct: 0.67, effect: 'Mood elevation' },
      { name: 'Linalool', pct: 0.45, effect: 'Calming' },
    ],
    effects: ['Sedated', 'Relaxed', 'Euphoric', 'Hungry'],
    flavors: ['Diesel', 'Grape', 'Berry', 'Earthy'],
    lineage: { mother: 'SFV OG', father: 'Bubba Kush' },
    labData: {
      lab: 'Green Leaf Lab',
      date: '2025-10-05',
      cannabinoids: [
        { name: 'THC', value: '26.3%' },
        { name: 'THCA', value: '29.7%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'CBDA', value: '0.2%' },
        { name: 'CBG', value: '0.6%' },
        { name: 'CBN', value: '0.5%' },
        { name: 'CBC', value: '0.3%' },
        { name: 'THCV', value: '0.1%' },
      ],
    },
    dispensaryIds: ['gorge-greens', 'cascadia-collective'],
    likeCount: 756,
    color: '#8b6fb8',
  },
  {
    id: 'uw-purple',
    name: 'UW Purple',
    type: 'indica',
    thc: 22.5,
    cbd: 0.2,
    source_state: 'WA',
    is_legacy: true,
    chemotype: 'Type I (THC-dominant)',
    description: 'A mythical indica born in the early 90s, supposedly liberated from a university research lab. It yields dense, frost-laden purple buds with a rich, earthy aroma woven with notes of dark grapes and berries. Renowned for its profound, deeply relaxing body high.',
    effects: ['Relaxed', 'Sleepy', 'Euphoric'],
    terpenes: [
      { name: 'Myrcene', pct: 1.2, effect: 'Sedating' },
      { name: 'Caryophyllene', pct: 0.6, effect: 'Stress Relief' },
      { name: 'Pinene', pct: 0.3, effect: 'Focus' }
    ],
    flavors: ['Grape', 'Earthy', 'Berry'],
    lineage: { mother: 'Unknown Indica', father: 'Unknown' },
    labData: { lab: 'Trace Analytics', date: '2025-10-15', cannabinoids: [] },
    dispensaryIds: ['have-a-heart-belltown', 'dockside-sodo'],
    likeCount: 2045,
    color: '#7858a8'
  },
  {
    id: 'pnw-hashplant',
    name: 'PNW Hashplant',
    type: 'indica',
    thc: 21.0,
    cbd: 0.5,
    source_state: 'WA',
    is_legacy: true,
    chemotype: 'Type I (THC-dominant)',
    description: 'A legendary foundation of Pacific Northwest cannabis culture. This stout, resilient plant produces massive amounts of sticky resin. Expect a thick, hashy smoke that delivers an immediate, numbing body buzz and intense physical relaxation.',
    effects: ['Relaxed', 'Hungry', 'Happy'],
    terpenes: [
      { name: 'Myrcene', pct: 1.5, effect: 'Sedating' },
      { name: 'Limonene', pct: 0.4, effect: 'Uplifting' }
    ],
    flavors: ['Hash', 'Woody', 'Earthy'],
    lineage: { mother: 'Afghani', father: 'Northern Lights' },
    labData: { lab: 'Trace Analytics', date: '2025-10-20', cannabinoids: [] },
    dispensaryIds: ['shawn-kemps'],
    likeCount: 1543,
    color: '#3a8c8a'
  },
  {
    id: 'sirius-black',
    name: 'Sirius Black',
    type: 'indica',
    thc: 24.0,
    cbd: 0.1,
    source_state: 'OR',
    is_legacy: true,
    chemotype: 'Type I (THC-dominant)',
    description: 'Bred in the 1980s by the Portland-based Oregon Breeders Group, this incredibly dark, almost pitch-black cultivar is a feast for the eyes. It offers a deeply sweet, jammy grape aroma and delivers a sedating, full-body euphoria.',
    effects: ['Sleepy', 'Relaxed', 'Uplifted'],
    terpenes: [
      { name: 'Linalool', pct: 0.8, effect: 'Calming' },
      { name: 'Myrcene', pct: 1.1, effect: 'Sedating' }
    ],
    flavors: ['Grape', 'Berry', 'Sweet'],
    lineage: { mother: 'Unknown', father: 'Unknown' },
    labData: { lab: 'Green Leaf Lab', date: '2025-11-01', cannabinoids: [] },
    dispensaryIds: ['happy-leaf', 'chalice-downtown'],
    likeCount: 3001,
    color: '#251428'
  },
  {
    id: 'marionberry-kush',
    name: 'Marionberry Kush',
    type: 'hybrid',
    thc: 23.5,
    cbd: 0.3,
    source_state: 'OR',
    is_legacy: true,
    chemotype: 'Type I (THC-dominant)',
    description: 'An homage to Oregon’s native blackberry cultivar, this 60/40 indica-leaning hybrid bursts with the sweet, tart aroma of freshly picked berries. The high is perfectly balanced, easing physical tension while leaving the mind sharp and creative.',
    effects: ['Creative', 'Relaxed', 'Happy'],
    terpenes: [
      { name: 'Caryophyllene', pct: 0.9, effect: 'Stress Relief' },
      { name: 'Limonene', pct: 0.7, effect: 'Uplifting' }
    ],
    flavors: ['Berry', 'Sweet', 'Earthy'],
    lineage: { mother: 'Raspberry Kush', father: 'Space Queen' },
    labData: { lab: 'Green Leaf Lab', date: '2025-11-05', cannabinoids: [] },
    dispensaryIds: ['farma'],
    likeCount: 2210,
    color: '#8b6fb8'
  },
  {
    id: 'dogwalker-og',
    name: 'Dogwalker OG',
    type: 'hybrid',
    thc: 26.0,
    cbd: 0.1,
    source_state: 'OR',
    is_legacy: true,
    chemotype: 'Type I (THC-dominant)',
    description: 'A potent cross of the heirloom Albert Walker and Chemdog 91, this cultivar earned its name from its exceptionally pungent, skunky, and earthy aroma. It delivers an incredibly strong, cerebrally focused high that melts into deep physical relaxation.',
    effects: ['Focused', 'Relaxed', 'Euphoric'],
    terpenes: [
      { name: 'Humulene', pct: 0.5, effect: 'Anti-inflammatory' },
      { name: 'Myrcene', pct: 1.0, effect: 'Sedating' }
    ],
    flavors: ['Skunk', 'Diesel', 'Earthy'],
    lineage: { mother: 'Albert Walker', father: 'Chemdog 91' },
    labData: { lab: 'Green Leaf Lab', date: '2025-10-30', cannabinoids: [] },
    dispensaryIds: ['happy-leaf', 'farma', 'floyds-fine-cannabis'],
    likeCount: 3450,
    color: '#c4831a'
  },
  {
    id: 'blue-dream',
    name: 'Blue Dream',
    type: 'hybrid',
    thc: 21.0,
    cbd: 0.1,
    terpenes: [
      { name: 'Myrcene', pct: 0.52, effect: 'Relaxing, sedating, earthy musk' },
      { name: 'Pinene', pct: 0.31, effect: 'Alertness, memory retention, piney freshness' },
      { name: 'Caryophyllene', pct: 0.22, effect: 'Anti-inflammatory, spicy, stress relief' },
    ],
    effects: ['Creative', 'Euphoric', 'Happy', 'Relaxed'],
    flavors: ['Berry', 'Blueberry', 'Sweet', 'Herbal'],
    lineage: { mother: 'Blueberry', father: 'Haze' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '21.0%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'THCA', value: '23.8%' },
        { name: 'CBG', value: '0.4%' },
        { name: 'CBN', value: '0.1%' },
      ],
    },
    dispensaryIds: ['green-needle', 'have-a-heart-belltown', 'happy-leaf', 'uncle-ikes-central', 'nectar-mississippi'],
    likeCount: 5200,
    chemotype: 'Type I (THC-dominant)',
    description:
      'A sativa-dominant hybrid born on the foggy California coast and fully claimed by the Pacific Northwest\'s creative culture. Blue Dream drifts in like morning marine layer — blueberry sweetness rising into a cerebral lift that clears space for ideas without walling off the body\'s ease. The strain that taught a generation of Seattle and Portland flower shops what balance actually means.',
    color: '#5B8DD9',
    source_state: 'WA',
  },
  {
    id: 'gg4',
    name: 'GG#4',
    type: 'hybrid',
    thc: 26.0,
    cbd: 0.1,
    terpenes: [
      { name: 'Caryophyllene', pct: 0.58, effect: 'Spicy, peppery, anti-inflammatory' },
      { name: 'Myrcene', pct: 0.44, effect: 'Earthy, sedating, muscle relaxation' },
      { name: 'Limonene', pct: 0.29, effect: 'Citrus lift, mood elevation, stress relief' },
    ],
    effects: ['Relaxed', 'Euphoric', 'Sleepy', 'Hungry'],
    flavors: ['Earthy', 'Pine', 'Pungent', 'Sour'],
    lineage: { mother: 'Chem\'s Sister', father: 'Sour Dubb' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '26.0%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'THCA', value: '29.5%' },
        { name: 'CBG', value: '0.5%' },
        { name: 'CBN', value: '0.2%' },
      ],
    },
    dispensaryIds: ['shawn-kemps', 'dockside-sodo', 'gorge-greens', 'uncle-ikes-central', 'uncle-ikes-capitol'],
    likeCount: 4000,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Heavy as Cascade snowpack and twice as persistent, GG#4 is the strain that turned "glued to the couch" into a wellness ritual for tired bodies up and down I-5. Chunky resin-lacquered buds carry an earthy diesel funk that hits like a cold rain — sudden, total, and transformative. Born from Chem genetics, it found its spiritual home among the tired Cascadian faithful who believe full-body release is its own form of medicine.',
    color: '#5C7A3E',
    source_state: 'WA',
  },
  {
    id: 'gelato-41',
    name: 'Gelato 41',
    type: 'hybrid',
    thc: 23.0,
    cbd: 0.1,
    terpenes: [
      { name: 'Caryophyllene', pct: 0.61, effect: 'Spicy warmth, pain modulation, calming' },
      { name: 'Limonene', pct: 0.38, effect: 'Citrus brightness, anti-anxiety, mood lift' },
      { name: 'Humulene', pct: 0.19, effect: 'Earthy, appetite suppressing, anti-inflammatory' },
      { name: 'Linalool', pct: 0.14, effect: 'Floral calm, sedation, stress relief' },
    ],
    effects: ['Euphoric', 'Relaxed', 'Creative', 'Happy'],
    flavors: ['Sweet', 'Citrus', 'Creamy', 'Berry'],
    lineage: { mother: 'Sunset Sherbet', father: 'Thin Mint GSC' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '23.0%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'THCA', value: '26.1%' },
        { name: 'CBG', value: '0.6%' },
        { name: 'CBN', value: '0.1%' },
      ],
    },
    dispensaryIds: ['cascadia-collective', 'farma', 'chalice-downtown', 'serra-downtown'],
    likeCount: 3500,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Gelato 41 arrives at the senses the way a late-summer Portland evening does — deep purples in the bud, a creamy sweetness that lingers like the last scoop before closing time, and a warmth that settles from the shoulders down. The balanced euphoria sits right at the edge of productive and pleasantly lost, making it the craft-focused dispensary\'s answer to those who refuse to choose between function and indulgence. Cookie genetics refined to their finest expression.',
    color: '#7B5EA7',
    source_state: 'OR',
  },
  {
    id: 'wedding-cake',
    name: 'Wedding Cake',
    type: 'hybrid',
    thc: 24.0,
    cbd: 0.1,
    terpenes: [
      { name: 'Caryophyllene', pct: 0.64, effect: 'Peppery depth, anti-inflammatory, grounding' },
      { name: 'Limonene', pct: 0.41, effect: 'Tangy uplift, mood brightening, stress reduction' },
      { name: 'Myrcene', pct: 0.33, effect: 'Musky sweetness, body relaxation, sedation' },
    ],
    effects: ['Relaxed', 'Euphoric', 'Hungry', 'Happy'],
    flavors: ['Vanilla', 'Pepper', 'Butter', 'Earthy'],
    lineage: { mother: 'Triangle Kush', father: 'Animal Mints' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '24.0%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'THCA', value: '27.2%' },
        { name: 'CBG', value: '1.0%' },
        { name: 'CBN', value: '0.1%' },
      ],
    },
    dispensaryIds: ['have-a-heart-belltown', 'green-needle', 'chalice-downtown', 'serra-downtown', 'chalice-powell'],
    likeCount: 3800,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Leafly\'s 2019 Strain of the Year carries the rich, tangy weight of a celebration you didn\'t have to plan — vanilla-pepper sweetness rising from dense, crystal-frosted buds that look like they were dusted in Pacific sea salt. Wedding Cake\'s indica-leaning warmth unwraps the body methodically from the shoulders to the ankles, letting the mind float just far enough above the noise to call it a good evening. Boutique dispensary shelves from Belltown to Portland\'s Pearl District move this one fast for a reason.',
    color: '#E8D5A3',
    source_state: 'WA',
  },
  {
    id: 'northern-lights',
    name: 'Northern Lights',
    type: 'indica',
    thc: 18.0,
    cbd: 0.1,
    terpenes: [
      { name: 'Myrcene', pct: 0.55, effect: 'Deep body calm, earthy sedation, sleep aid' },
      { name: 'Caryophyllene', pct: 0.34, effect: 'Spicy warmth, pain relief, anti-anxiety' },
      { name: 'Limonene', pct: 0.21, effect: 'Subtle citrus, mood balance, stress lift' },
    ],
    effects: ['Sleepy', 'Relaxed', 'Euphoric', 'Hungry'],
    flavors: ['Pine', 'Earthy', 'Woody', 'Sweet'],
    lineage: { mother: 'Afghani', father: 'Thai' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '18.0%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'THCA', value: '20.4%' },
        { name: 'CBG', value: '1.0%' },
        { name: 'CBN', value: '0.2%' },
      ],
    },
    dispensaryIds: ['shawn-kemps', 'rainforest-remedies', 'gorge-greens', 'uncle-ikes-capitol'],
    likeCount: 4500,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Rumor has it Northern Lights first reached its roots into Puget Sound soil before Holland\'s Sensi Seeds carried it to legend — and the PNW has never stopped feeling that quiet ownership. Pure Afghani-dominant resin architecture wraps the body in the kind of dense, piney warmth that only comes from old-growth forests and serious genetics. This is the strain that turns a Washington winter night into something worth sinking into.',
    color: '#2E5E4E',
    source_state: 'WA',
  },
  {
    id: 'granddaddy-purple',
    name: 'Granddaddy Purple',
    type: 'indica',
    thc: 17.0,
    cbd: 0.1,
    terpenes: [
      { name: 'Myrcene', pct: 0.57, effect: 'Grape-musky calm, body lock, sleep onset' },
      { name: 'Pinene', pct: 0.30, effect: 'Pine clarity, memory, airway opening' },
      { name: 'Caryophyllene', pct: 0.24, effect: 'Spicy undertone, pain modulation, anti-stress' },
    ],
    effects: ['Sleepy', 'Relaxed', 'Euphoric', 'Hungry'],
    flavors: ['Grape', 'Berry', 'Floral', 'Sweet'],
    lineage: { mother: 'Mendo Purps', father: 'Afghani' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '17.0%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'THCA', value: '19.3%' },
        { name: 'CBG', value: '0.4%' },
        { name: 'CBN', value: '0.3%' },
      ],
    },
    dispensaryIds: ['shawn-kemps', 'happy-leaf', 'rainforest-remedies', 'floyds-fine-cannabis'],
    likeCount: 4200,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Ken Estes\'s 2003 California masterwork found its most devoted congregation in the Pacific Northwest, where the long grey evenings create the perfect condition for GDP\'s royal purple hues and grape-laden embrace. Deep myrcene-forward sedation arrives with a cerebral warmth that makes the ceiling seem very far away in the best possible sense — the Oregon coast\'s way of saying the day is done and rest is earned. No other indica communicates closure quite as eloquently.',
    color: '#6B3FA0',
    source_state: 'OR',
  },
  {
    id: 'sour-diesel',
    name: 'Sour Diesel',
    type: 'sativa',
    thc: 22.0,
    cbd: 0.2,
    terpenes: [
      { name: 'Caryophyllene', pct: 0.48, effect: 'Peppery fuel note, anti-inflammatory, focus' },
      { name: 'Myrcene', pct: 0.33, effect: 'Earthy base, body ease, edge softening' },
      { name: 'Limonene', pct: 0.29, effect: 'Citrus charge, mood elevation, mental clarity' },
      { name: 'Terpinolene', pct: 0.17, effect: 'Herbal uplift, energizing, pine-fresh' },
    ],
    effects: ['Energetic', 'Euphoric', 'Creative', 'Focused'],
    flavors: ['Diesel', 'Citrus', 'Earthy', 'Herbal'],
    lineage: { mother: 'Chemdog 91', father: 'Super Skunk' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '22.0%' },
        { name: 'CBD', value: '0.2%' },
        { name: 'THCA', value: '24.9%' },
        { name: 'CBG', value: '0.5%' },
        { name: 'CBN', value: '0.1%' },
      ],
    },
    dispensaryIds: ['green-needle', 'dockside-sodo', 'farma', 'uncle-ikes-central', 'floyds-fine-cannabis'],
    likeCount: 4800,
    chemotype: 'Type I (THC-dominant)',
    description:
      'East Coast in origin but Pacific Northwest in attitude — Sour Diesel hits like the first espresso of a grey Seattle morning, all fuel and forward motion with nowhere to be but fully, electrically present. The sharp diesel-citrus punch clears mental fog like a Columbia Gorge wind event, leaving behind a fast-moving cerebral energy that creative professionals and trail runners up and down the coast have relied on for decades. Nothing about this strain apologizes for wanting to get things done.',
    color: '#D4A017',
    source_state: 'WA',
  },
  {
    id: 'acdc',
    name: 'ACDC',
    type: 'hybrid',
    thc: 1.0,
    cbd: 20.0,
    terpenes: [
      { name: 'Myrcene', pct: 0.44, effect: 'Grounding calm, anti-inflammatory, relaxation without intoxication' },
      { name: 'Pinene', pct: 0.38, effect: 'Mental clarity, airway support, alertness' },
      { name: 'Caryophyllene', pct: 0.27, effect: 'Anti-inflammatory, analgesic, gentle body warmth' },
      { name: 'Ocimene', pct: 0.12, effect: 'Sweet floral lift, subtle mood support' },
    ],
    effects: ['Relaxed', 'Focused', 'Happy', 'Uplifted'],
    flavors: ['Earthy', 'Woody', 'Pine', 'Sweet'],
    lineage: { mother: 'Cannatonic', father: null },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '1.0%' },
        { name: 'CBD', value: '20.0%' },
        { name: 'THCA', value: '1.1%' },
        { name: 'CBDA', value: '22.7%' },
        { name: 'CBG', value: '0.3%' },
      ],
    },
    dispensaryIds: ['rainforest-remedies', 'cascadia-collective', 'gorge-greens', 'nectar-mississippi', 'chalice-powell'],
    likeCount: 1800,
    chemotype: 'Type III (CBD-dominant)',
    description:
      'ACDC is the strain that reshaped what Pacific Northwest wellness dispensaries are for — a near-CBD-pure cultivar that delivers therapeutic depth without a whisper of intoxication, perfect for the Olympia wellness community that takes its medicine seriously. Cannatonic heritage gives it a clean earthy-pine profile, and the anxiety and inflammation relief it provides has made it the go-to for patients who want the plant\'s gifts without any interruption to their day. Oregon\'s craft CBD growers have elevated this cultivar into a regional specialty.',
    color: '#4A7A55',
    source_state: 'OR',
  },
  {
    id: 'harlequin',
    name: 'Harlequin',
    type: 'hybrid',
    thc: 7.0,
    cbd: 12.0,
    terpenes: [
      { name: 'Myrcene', pct: 0.46, effect: 'Mellow body ease, earthy warmth, gentle sedation' },
      { name: 'Caryophyllene', pct: 0.35, effect: 'Anti-inflammatory, spicy roundness, pain relief' },
      { name: 'Pinene', pct: 0.28, effect: 'Mental alertness, counteracts THC cloudiness, fresh pine' },
    ],
    effects: ['Relaxed', 'Focused', 'Happy', 'Uplifted'],
    flavors: ['Earthy', 'Mango', 'Woody', 'Citrus'],
    lineage: { mother: 'Colombian Gold', father: 'Nepali' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '7.0%' },
        { name: 'CBD', value: '12.0%' },
        { name: 'THCA', value: '7.9%' },
        { name: 'CBDA', value: '13.6%' },
        { name: 'CBG', value: '0.4%' },
      ],
    },
    dispensaryIds: ['rainforest-remedies', 'farma', 'cascadia-collective', 'nectar-mississippi', 'floyds-fine-cannabis'],
    likeCount: 2000,
    chemotype: 'Type II (Balanced CBD/THC)',
    description:
      'Harlequin is the strain that finally gave the Pacific Northwest\'s medical community a bridge between worlds — enough THC to feel the plant\'s social warmth, enough CBD to keep the mind clear and the body easy through a full workday in the rain. The mango-earth terpene profile carries a quiet exoticism from its Colombian and Nepali landrace ancestry, grounded by the clean air of Oregon\'s Willamette Valley where it thrives. Farma and the region\'s curated wellness shops consider it essential stock for the clear-headed patient.',
    color: '#E8A44A',
    source_state: 'OR',
  },
  {
    id: 'jack-herer',
    name: 'Jack Herer',
    type: 'sativa',
    thc: 18.0,
    cbd: 0.1,
    terpenes: [
      { name: 'Terpinolene', pct: 0.52, effect: 'Floral-herbal uplift, energizing, creativity driver' },
      { name: 'Pinene', pct: 0.36, effect: 'Pine clarity, memory retention, bronchial opening' },
      { name: 'Caryophyllene', pct: 0.24, effect: 'Spicy depth, anti-inflammatory, stress buffer' },
      { name: 'Ocimene', pct: 0.15, effect: 'Sweet herbal brightness, antifungal, uplifting' },
    ],
    effects: ['Creative', 'Energetic', 'Euphoric', 'Focused'],
    flavors: ['Pine', 'Earthy', 'Woody', 'Spicy'],
    lineage: { mother: 'Northern Lights #5', father: 'Shiva Skunk' },
    labData: {
      lab: 'Leafly aggregate',
      date: '2025-01-01',
      cannabinoids: [
        { name: 'THC', value: '18.0%' },
        { name: 'CBD', value: '0.1%' },
        { name: 'THCA', value: '20.4%' },
        { name: 'CBG', value: '0.6%' },
        { name: 'CBN', value: '0.1%' },
      ],
    },
    dispensaryIds: ['green-needle', 'cascadia-collective', 'dockside-sodo', 'uncle-ikes-central', 'uncle-ikes-capitol'],
    likeCount: 4400,
    chemotype: 'Type I (THC-dominant)',
    description:
      'Named for the cannabis activist and author who believed the plant could change the world, Jack Herer carries that conviction in its terpene profile — a bright Sensi Seeds pedigree of pine, spice, and herbal focus that feels less like getting high and more like getting clear. The strain connects naturally to the Pacific Northwest\'s activist and outdoor culture, where its energizing terpinolene-forward lift pairs equally well with a morning trail run in the Olympics or an afternoon of ideation at a Portland co-working space. This is the people\'s strain for the conscious consumer.',
    color: '#8B7355',
    source_state: 'WA',
  }
];

export const DISPENSARIES: Dispensary[] = [
  {
    id: 'green-needle',
    name: 'Green Needle Cannabis',
    address: '1847 15th Ave E',
    city: 'Seattle',
    state: 'WA',
    coordinates: { lat: 47.6219, lng: -122.308 },
    hours: 'Mon–Sat 9am–10pm · Sun 10am–8pm',
    phone: '(206) 555-0142',
    strainIds: ['cascadia-haze', 'rainier-kush', 'olympic-fog', 'blue-dream', 'wedding-cake', 'jack-herer'],
    rating: 4.8,
  },
  {
    id: 'cascadia-collective',
    name: 'Cascadia Collective',
    address: '2241 NE Alberta St',
    city: 'Portland',
    state: 'OR',
    coordinates: { lat: 45.558, lng: -122.6393 },
    hours: 'Daily 8am–11pm',
    phone: '(503) 555-0287',
    strainIds: [
      'cascadia-haze',
      'hood-river-haze',
      'puget-sound-cbd',
      'willamette-valley-og',
      'gelato-41',
      'acdc',
      'harlequin',
      'jack-herer'
    ],
    rating: 4.9,
  },
  {
    id: 'rainforest-remedies',
    name: 'Rainforest Remedies',
    address: '420 4th Ave E',
    city: 'Olympia',
    state: 'WA',
    coordinates: { lat: 47.0432, lng: -122.9007 },
    hours: 'Mon–Sat 10am–9pm · Sun 11am–7pm',
    phone: '(360) 555-0318',
    strainIds: ['rainier-kush', 'olympic-fog', 'puget-sound-cbd', 'northern-lights', 'granddaddy-purple', 'acdc', 'harlequin'],
    rating: 4.7,
  },
  {
    id: 'gorge-greens',
    name: 'Gorge Greens',
    address: '312 Oak St',
    city: 'Hood River',
    state: 'OR',
    coordinates: { lat: 45.7131, lng: -121.5195 },
    hours: 'Daily 9am–9pm',
    phone: '(541) 555-0463',
    strainIds: ['hood-river-haze', 'willamette-valley-og', 'gg4', 'northern-lights', 'acdc'],
    rating: 4.6,
  },
  {
    id: 'have-a-heart-belltown',
    name: 'Have a Heart (Belltown)',
    address: '115 Blanchard St',
    city: 'Seattle',
    state: 'WA',
    coordinates: { lat: 47.6136, lng: -122.3431 },
    hours: '8:00 AM - 11:45 PM',
    phone: '(206) 555-1111',
    strainIds: ['uw-purple', 'blue-dream', 'wedding-cake'],
    rating: 4.8,
  },
  {
    id: 'dockside-sodo',
    name: 'Dockside Cannabis (SODO)',
    address: '1728 4th Ave S',
    city: 'Seattle',
    state: 'WA',
    coordinates: { lat: 47.5880, lng: -122.3292 },
    hours: '8:00 AM - 11:30 PM',
    phone: '(206) 555-2222',
    strainIds: ['uw-purple', 'gg4', 'sour-diesel', 'jack-herer'],
    rating: 4.7,
  },
  {
    id: 'shawn-kemps',
    name: 'Shawn Kemp’s Cannabis',
    address: '3035 1st Ave',
    city: 'Seattle',
    state: 'WA',
    coordinates: { lat: 47.6166, lng: -122.3533 },
    hours: '8:00 AM - 11:45 PM',
    phone: '(206) 555-3333',
    strainIds: ['pnw-hashplant', 'gg4', 'northern-lights', 'granddaddy-purple'],
    rating: 4.9,
  },
  {
    id: 'happy-leaf',
    name: 'Happy Leaf',
    address: '1301 NE Broadway St',
    city: 'Portland',
    state: 'OR',
    coordinates: { lat: 45.5350, lng: -122.6517 },
    hours: '10:00 AM - 10:00 PM',
    phone: '(503) 555-4444',
    strainIds: ['sirius-black', 'dogwalker-og', 'blue-dream', 'granddaddy-purple'],
    rating: 4.6,
  },
  {
    id: 'chalice-downtown',
    name: 'Chalice Cannabis (Downtown)',
    address: '823 SW Naito Pkwy',
    city: 'Portland',
    state: 'OR',
    coordinates: { lat: 45.5165, lng: -122.6738 },
    hours: '10:00 AM - 9:00 PM',
    phone: '(503) 555-5555',
    strainIds: ['sirius-black', 'gelato-41', 'wedding-cake'],
    rating: 4.8,
  },
  {
    id: 'farma',
    name: 'Farma',
    address: '916 SE Hawthorne Blvd',
    city: 'Portland',
    state: 'OR',
    coordinates: { lat: 45.5123, lng: -122.6565 },
    hours: '10:00 AM - 9:30 PM',
    phone: '(503) 555-6666',
    strainIds: ['marionberry-kush', 'dogwalker-og', 'gelato-41', 'sour-diesel', 'harlequin'],
    rating: 4.9,
  },
  {
    id: 'uncle-ikes-central',
    name: 'Uncle Ike\'s (Central)',
    address: '2310 E Union St',
    city: 'Seattle',
    state: 'WA',
    coordinates: { lat: 47.6131, lng: -122.3065 },
    hours: '8:00 AM - 11:59 PM',
    phone: '(206) 555-7777',
    strainIds: ['blue-dream', 'sour-diesel', 'jack-herer', 'gg4'],
    rating: 4.5,
  },
  {
    id: 'serra-downtown',
    name: 'Serra (Downtown)',
    address: '220 SW 1st Ave',
    city: 'Portland',
    state: 'OR',
    coordinates: { lat: 45.5228, lng: -122.6775 },
    hours: '10:00 AM - 10:00 PM',
    phone: '(503) 555-8888',
    strainIds: ['gelato-41', 'wedding-cake', 'sirius-black'],
    rating: 4.8,
  },
  {
    id: 'nectar-mississippi',
    name: 'Nectar (Mississippi)',
    address: '3350 N Mississippi Ave',
    city: 'Portland',
    state: 'OR',
    coordinates: { lat: 45.5518, lng: -122.6756 },
    hours: '9:00 AM - 10:00 PM',
    phone: '(503) 555-9999',
    strainIds: ['acdc', 'harlequin', 'blue-dream'],
    rating: 4.7,
  },
  {
    id: 'uncle-ikes-capitol',
    name: 'Uncle Ike\'s (Capitol Hill)',
    address: '501 15th Ave E',
    city: 'Seattle',
    state: 'WA',
    coordinates: { lat: 47.6152, lng: -122.3204 },
    hours: '8:00 AM - 11:59 PM',
    phone: '(206) 555-8899',
    strainIds: ['jack-herer', 'northern-lights', 'gg4'],
    rating: 4.6,
  },
  {
    id: 'floyds-fine-cannabis',
    name: 'Floyd\'s Fine Cannabis',
    address: '2030 NE Sandy Blvd',
    city: 'Portland',
    state: 'OR',
    coordinates: { lat: 45.5235, lng: -122.6328 },
    hours: '9:00 AM - 10:00 PM',
    phone: '(503) 555-2211',
    strainIds: ['granddaddy-purple', 'sour-diesel', 'harlequin', 'dogwalker-og'],
    rating: 4.7,
  },
  {
    id: 'chalice-powell',
    name: 'Chalice Cannabis (Powell)',
    address: '5333 SE Powell Blvd',
    city: 'Portland',
    state: 'OR',
    coordinates: { lat: 45.4971, lng: -122.6042 },
    hours: '9:00 AM - 10:00 PM',
    phone: '(503) 555-3344',
    strainIds: ['acdc', 'wedding-cake', 'sirius-black'],
    rating: 4.5,
  }
];

export const TRIP_REPORTS: TripReport[] = [
  {
    id: 'tr-001',
    strainId: 'cascadia-haze',
    userId: 'u-emeraldcity88',
    username: 'emeraldcity88',
    rating: 5,
    effects: ['Euphoric', 'Creative', 'Focused'],
    method: 'flower',
    note:
      'Perfect Saturday morning strain. Two bowls and I spent four hours painting — best creative session I have had in months. The citrus is unmistakable on the inhale. Zero anxiety, just pure headspace.',
    upvotes: 142,
    downvotes: 3,
    createdAt: '2025-10-22',
  },
  {
    id: 'tr-002',
    strainId: 'cascadia-haze',
    userId: 'u-mthood-rider',
    username: 'mthood_rider',
    rating: 4,
    effects: ['Energetic', 'Creative'],
    method: 'vape',
    note:
      'Great for daytime use on the mountain. Clear-headed high with good energy. Lasted about 2 hours via vape. Slight dry mouth but manageable. Would buy again for active sessions.',
    upvotes: 87,
    downvotes: 8,
    createdAt: '2025-11-01',
  },
  {
    id: 'tr-003',
    strainId: 'cascadia-haze',
    userId: 'u-pnwpetals',
    username: 'pnwpetals',
    rating: 5,
    effects: ['Euphoric', 'Happy', 'Talkative'],
    method: 'flower',
    note:
      'My go-to for social situations. Not overwhelming, just opens you up. The terpene profile is genuinely complex — I taste the terpinolene and ocimene clearly. Lab cert checks out with what Confidence Analytics reported.',
    upvotes: 210,
    downvotes: 5,
    createdAt: '2025-11-10',
  },
];

export const MEDIA_ITEMS: MediaItem[] = [
  { id: 'm1', category: 'Science', title: 'How Terpinolene Shapes the Sativa Experience', thumb: '🔬', date: 'Nov 14' },
  { id: 'm2', category: 'PNW', title: "Inside the Gorge: Hood River's Growing Scene", thumb: '🏔️', date: 'Nov 12' },
  { id: 'm3', category: 'How-To', title: 'Reading a Lab Certificate of Analysis', thumb: '📋', date: 'Nov 10' },
  { id: 'm4', category: 'Terpenes', title: 'Myrcene vs. Linalool: The Calming Duo Explained', thumb: '🌿', date: 'Nov 8' },
  { id: 'm5', category: 'Science', title: 'Genetic Lineage and Why It Predicts Your High', thumb: '🧬', date: 'Nov 6' },
  { id: 'm6', category: 'PNW', title: "Oregon's Craft Cannabis Farmers: A Visual Story", thumb: '🌲', date: 'Nov 4' },
  { id: 'm7', category: 'How-To', title: 'Building Your Personal Strain Library', thumb: '📚', date: 'Nov 2' },
  { id: 'm8', category: 'Terpenes', title: 'The Citrus-Pine Profile: A PNW Signature', thumb: '🍋', date: 'Oct 30' },
];

export const DEFAULT_USER: UserProfile = {
  id: 'demo',
  username: 'demo',
  showRealName: false,
  tier: 'free',
};
